### ISSUE TITLE
Crash on linux path names

### ISSUE THREAD

**Issue by rockerBOO** [jndietz/caption-captain#5]
I think this error is due to the slash that needs to be OS specific. 

Image folder path: `/mnt/900/input/cyberpunk-anime/201`

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open '/mnt/900/input/cyberpunk-anime/201\00000-0-vlcsnap-2023-02-18-16h30m22s513.png'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/mnt/900/input/cyberpunk-anime/201\\00000-0-vlcsnap-2023-02-18-16h30m22s513.png'
}

Node.js v18.15.0
```

**Comment by jndietz** [comment]
Thank you for the report!  I think I know the issue...

**Comment by jndietz** [comment]
@rockerBOO  This should be resolved now.  Can you `git pull` and give it a shot?  I updated it so that express uses `/` instead of `\\` where paths are used.  I tested it in WSL and Powershell, so I hope it works for you too :)

**Comment by rockerBOO** [comment]
cool, works!

**Comment by jndietz** [comment]
Thank you so much for testing this out and following up!

**Comment by notfood** [comment]
It's not completely solved, during writing captions it writes the filename as `\caption.txt`

```js
{
  filename: '/media/Makai/home/Desktop/silkies/15_silkie chicken_2/\\silkie_33.txt',
  caption: 'silkie chicken, full body, from side, profile, leg up'
}
```

Possible source of the issue: https://github.com/jndietz/caption-captain/blob/main/src/components/Caption/CaptionTemplateForm.jsx#L103

**Comment by jndietz** [comment]
@notfood  Thanks for the report - hopefully this is resolved for good now.  I updated the line of code you provided to use a `/` instead of `\\`.  I tested it running in Powershell, so it should work now in Linux as well.
